/* Generated by scripts/generate-code-pages.mjs — do not edit. */

/**
 * Every hand-written page component under `inertia/custom/pages/`.
 *
 * Read by `PagesService` to reject a CODE page whose component does not
 * exist, and served to the admin page-create dialog so the picker only ever
 * offers real files.
 */
export const CODE_PAGES: readonly string[] = ['playground']
