/* Generated by scripts/generate-custom-templates.mjs — do not edit. */

/**
 * Every custom-template kit under `inertia/custom/kits/` (a folder with a
 * `kit.json` marker + `index.tsx` entry).
 *
 * Read by `PagesService` to reject a CODE page whose `kit:<id>` component does
 * not exist, and served to the admin / MCP page-create pickers so they only
 * ever offer real kits. `id` is the folder name and the value stored as
 * `page.component = "kit:<id>"`.
 */
export interface CustomTemplate {
  id: string
  name: string
  description: string
}

export const CUSTOM_TEMPLATES: readonly CustomTemplate[] = [
  {
    "id": "example",
    "name": "Example kit",
    "description": "A starter custom template — copy this folder, rename it, and point a page at it."
  }
]
