services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driftless
    volumes:
      - driftless_pg_data:/var/lib/postgresql/data

volumes:
  driftless_pg_data:
