import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Album,
  Anchor,
  Archive,
  AtSign,
  Award,
  Banknote,
  Bell,
  BellRing,
  Binary,
  Bluetooth,
  BookCopy,
  Bookmark,
  BookMarked,
  BookOpen,
  Bot,
  Boxes,
  BrickWall,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Camera,
  Car,
  Castle,
  ChartBar,
  ChartLine,
  ChartPie,
  CheckCircle,
  ChefHat,
  Church,
  CircleDollarSign,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Coins,
  Compass,
  Construction,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  Disc3,
  Dog,
  Download,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  ExternalLink,
  Eye,
  Factory,
  Fan,
  Feather,
  FileSpreadsheet,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderTree,
  Footprints,
  Forward,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Grid3x3,
  Guitar,
  Hammer,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Highlighter,
  History,
  Hospital,
  Hotel,
  Hourglass,
  IceCream2,
  Image as ImageIcon,
  ImagePlus,
  Inbox,
  Info,
  Joystick,
  Kanban,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Layers,
  LayoutList,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  Locate,
  Lock,
  LockKeyhole,
  LogIn,
  Luggage,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Music2,
  Navigation,
  Navigation2,
  Network,
  Newspaper,
  Nut,
  Octagon,
  Package,
  PackageOpen,
  Paintbrush,
  Palette,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pencil,
  PenLine,
  Percent,
  Phone,
  Piano,
  PiggyBank,
  Pin,
  Pizza,
  Plane,
  Play,
  Plug,
  Podcast,
  Puzzle,
  Quote,
  Radio,
  Receipt,
  Recycle,
  Rocket,
  Rss,
  School,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sword,
  Tag,
  Tags,
  Target,
  Tent,
  Terminal,
  TestTube,
  Ticket,
  TrainFront,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Type,
  Umbrella,
  User,
  UserRound,
  Users,
  UsersRound,
  Video,
  Wallet,
  Warehouse,
  Wheat,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Curated Lucide icons for collection sidebar / forms (order = suggested priority, then A–Z).
 */
export const COLLECTION_PRESET_ICONS: ReadonlyArray<{
  name: string;
  Icon: LucideIcon;
}> = [
  { name: "LayoutList", Icon: LayoutList },
  { name: "FileText", Icon: FileText },
  { name: "BookOpen", Icon: BookOpen },
  { name: "Newspaper", Icon: Newspaper },
  { name: "Image", Icon: ImageIcon },
  { name: "Users", Icon: Users },
  { name: "Boxes", Icon: Boxes },
  { name: "Folder", Icon: Folder },
  { name: "Tag", Icon: Tag },
  { name: "Layers", Icon: Layers },
  { name: "Grid3x3", Icon: Grid3x3 },
  { name: "ClipboardList", Icon: ClipboardList },
  { name: "ShoppingBag", Icon: ShoppingBag },
  { name: "Package", Icon: Package },
  { name: "Briefcase", Icon: Briefcase },
  { name: "Calendar", Icon: Calendar },
  { name: "FileSpreadsheet", Icon: FileSpreadsheet },
  { name: "Megaphone", Icon: Megaphone },
  { name: "Star", Icon: Star },
  { name: "Heart", Icon: Heart },
  { name: "PenLine", Icon: PenLine },
  { name: "Sparkles", Icon: Sparkles },
  { name: "Activity", Icon: Activity },
  { name: "Album", Icon: Album },
  { name: "Anchor", Icon: Anchor },
  { name: "Archive", Icon: Archive },
  { name: "AtSign", Icon: AtSign },
  { name: "Award", Icon: Award },
  { name: "Banknote", Icon: Banknote },
  { name: "Bell", Icon: Bell },
  { name: "BellRing", Icon: BellRing },
  { name: "Binary", Icon: Binary },
  { name: "Bluetooth", Icon: Bluetooth },
  { name: "BookCopy", Icon: BookCopy },
  { name: "BookMarked", Icon: BookMarked },
  { name: "Bookmark", Icon: Bookmark },
  { name: "Bot", Icon: Bot },
  { name: "BrickWall", Icon: BrickWall },
  { name: "Brush", Icon: Brush },
  { name: "Bug", Icon: Bug },
  { name: "Building", Icon: Building },
  { name: "Building2", Icon: Building2 },
  { name: "Bus", Icon: Bus },
  { name: "Cake", Icon: Cake },
  { name: "Calculator", Icon: Calculator },
  { name: "CalendarClock", Icon: CalendarClock },
  { name: "CalendarDays", Icon: CalendarDays },
  { name: "CalendarRange", Icon: CalendarRange },
  { name: "Camera", Icon: Camera },
  { name: "Car", Icon: Car },
  { name: "Castle", Icon: Castle },
  { name: "ChartBar", Icon: ChartBar },
  { name: "ChartLine", Icon: ChartLine },
  { name: "ChartPie", Icon: ChartPie },
  { name: "CheckCircle", Icon: CheckCircle },
  { name: "ChefHat", Icon: ChefHat },
  { name: "Church", Icon: Church },
  { name: "CircleDollarSign", Icon: CircleDollarSign },
  { name: "Clapperboard", Icon: Clapperboard },
  { name: "Clock", Icon: Clock },
  { name: "Cloud", Icon: Cloud },
  { name: "CloudRain", Icon: CloudRain },
  { name: "Code", Icon: Code },
  { name: "Coffee", Icon: Coffee },
  { name: "Coins", Icon: Coins },
  { name: "Compass", Icon: Compass },
  { name: "Construction", Icon: Construction },
  { name: "Cookie", Icon: Cookie },
  { name: "Copy", Icon: Copy },
  { name: "Cpu", Icon: Cpu },
  { name: "CreditCard", Icon: CreditCard },
  { name: "Crown", Icon: Crown },
  { name: "Database", Icon: Database },
  { name: "Diamond", Icon: Diamond },
  { name: "Disc3", Icon: Disc3 },
  { name: "Dog", Icon: Dog },
  { name: "Download", Icon: Download },
  { name: "Droplets", Icon: Droplets },
  { name: "Dumbbell", Icon: Dumbbell },
  { name: "Ear", Icon: Ear },
  { name: "Egg", Icon: Egg },
  { name: "ExternalLink", Icon: ExternalLink },
  { name: "Eye", Icon: Eye },
  { name: "Factory", Icon: Factory },
  { name: "Fan", Icon: Fan },
  { name: "Feather", Icon: Feather },
  { name: "Film", Icon: Film },
  { name: "Fish", Icon: Fish },
  { name: "Flag", Icon: Flag },
  { name: "Flame", Icon: Flame },
  { name: "FlaskConical", Icon: FlaskConical },
  { name: "FolderOpen", Icon: FolderOpen },
  { name: "FolderTree", Icon: FolderTree },
  { name: "Footprints", Icon: Footprints },
  { name: "Forward", Icon: Forward },
  { name: "Fuel", Icon: Fuel },
  { name: "Gamepad2", Icon: Gamepad2 },
  { name: "Gauge", Icon: Gauge },
  { name: "Gem", Icon: Gem },
  { name: "Ghost", Icon: Ghost },
  { name: "Gift", Icon: Gift },
  { name: "GitBranch", Icon: GitBranch },
  { name: "Globe", Icon: Globe },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "Guitar", Icon: Guitar },
  { name: "Hammer", Icon: Hammer },
  { name: "HardDrive", Icon: HardDrive },
  { name: "Hash", Icon: Hash },
  { name: "Headphones", Icon: Headphones },
  { name: "HeartPulse", Icon: HeartPulse },
  { name: "Hexagon", Icon: Hexagon },
  { name: "Highlighter", Icon: Highlighter },
  { name: "History", Icon: History },
  { name: "Hospital", Icon: Hospital },
  { name: "Hotel", Icon: Hotel },
  { name: "Hourglass", Icon: Hourglass },
  { name: "IceCream2", Icon: IceCream2 },
  { name: "ImagePlus", Icon: ImagePlus },
  { name: "Inbox", Icon: Inbox },
  { name: "Info", Icon: Info },
  { name: "Joystick", Icon: Joystick },
  { name: "Kanban", Icon: Kanban },
  { name: "KeyRound", Icon: KeyRound },
  { name: "Lamp", Icon: Lamp },
  { name: "Landmark", Icon: Landmark },
  { name: "Laptop", Icon: Laptop },
  { name: "Leaf", Icon: Leaf },
  { name: "Library", Icon: Library },
  { name: "LifeBuoy", Icon: LifeBuoy },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Link2", Icon: Link2 },
  { name: "List", Icon: List },
  { name: "ListChecks", Icon: ListChecks },
  { name: "ListOrdered", Icon: ListOrdered },
  { name: "ListTodo", Icon: ListTodo },
  { name: "Locate", Icon: Locate },
  { name: "Lock", Icon: Lock },
  { name: "LockKeyhole", Icon: LockKeyhole },
  { name: "LogIn", Icon: LogIn },
  { name: "Luggage", Icon: Luggage },
  { name: "Mail", Icon: Mail },
  { name: "Map", Icon: Map },
  { name: "MapPin", Icon: MapPin },
  { name: "Medal", Icon: Medal },
  { name: "MessageCircle", Icon: MessageCircle },
  { name: "Mic", Icon: Mic },
  { name: "Monitor", Icon: Monitor },
  { name: "Moon", Icon: Moon },
  { name: "Music", Icon: Music },
  { name: "Music2", Icon: Music2 },
  { name: "Navigation", Icon: Navigation },
  { name: "Navigation2", Icon: Navigation2 },
  { name: "Network", Icon: Network },
  { name: "Nut", Icon: Nut },
  { name: "Octagon", Icon: Octagon },
  { name: "PackageOpen", Icon: PackageOpen },
  { name: "Paintbrush", Icon: Paintbrush },
  { name: "Palette", Icon: Palette },
  { name: "Paperclip", Icon: Paperclip },
  { name: "PartyPopper", Icon: PartyPopper },
  { name: "PawPrint", Icon: PawPrint },
  { name: "Pencil", Icon: Pencil },
  { name: "Percent", Icon: Percent },
  { name: "Phone", Icon: Phone },
  { name: "Piano", Icon: Piano },
  { name: "PiggyBank", Icon: PiggyBank },
  { name: "Pin", Icon: Pin },
  { name: "Pizza", Icon: Pizza },
  { name: "Plane", Icon: Plane },
  { name: "Play", Icon: Play },
  { name: "Plug", Icon: Plug },
  { name: "Podcast", Icon: Podcast },
  { name: "Puzzle", Icon: Puzzle },
  { name: "Quote", Icon: Quote },
  { name: "Radio", Icon: Radio },
  { name: "Receipt", Icon: Receipt },
  { name: "Recycle", Icon: Recycle },
  { name: "Rocket", Icon: Rocket },
  { name: "Rss", Icon: Rss },
  { name: "School", Icon: School },
  { name: "Search", Icon: Search },
  { name: "Send", Icon: Send },
  { name: "Server", Icon: Server },
  { name: "Settings", Icon: Settings },
  { name: "Settings2", Icon: Settings2 },
  { name: "Share2", Icon: Share2 },
  { name: "Shield", Icon: Shield },
  { name: "ShieldCheck", Icon: ShieldCheck },
  { name: "Ship", Icon: Ship },
  { name: "ShoppingCart", Icon: ShoppingCart },
  { name: "Smartphone", Icon: Smartphone },
  { name: "Snowflake", Icon: Snowflake },
  { name: "Sofa", Icon: Sofa },
  { name: "Speaker", Icon: Speaker },
  { name: "Sprout", Icon: Sprout },
  { name: "Stethoscope", Icon: Stethoscope },
  { name: "Store", Icon: Store },
  { name: "Sun", Icon: Sun },
  { name: "Sword", Icon: Sword },
  { name: "Tags", Icon: Tags },
  { name: "Target", Icon: Target },
  { name: "Tent", Icon: Tent },
  { name: "Terminal", Icon: Terminal },
  { name: "TestTube", Icon: TestTube },
  { name: "Ticket", Icon: Ticket },
  { name: "TrainFront", Icon: TrainFront },
  { name: "TreePine", Icon: TreePine },
  { name: "TrendingUp", Icon: TrendingUp },
  { name: "Trophy", Icon: Trophy },
  { name: "Truck", Icon: Truck },
  { name: "Tv", Icon: Tv },
  { name: "Type", Icon: Type },
  { name: "Umbrella", Icon: Umbrella },
  { name: "User", Icon: User },
  { name: "UserRound", Icon: UserRound },
  { name: "UsersRound", Icon: UsersRound },
  { name: "Video", Icon: Video },
  { name: "Wallet", Icon: Wallet },
  { name: "Warehouse", Icon: Warehouse },
  { name: "Wheat", Icon: Wheat },
  { name: "Wifi", Icon: Wifi },
  { name: "Wine", Icon: Wine },
  { name: "Wrench", Icon: Wrench },
  { name: "Zap", Icon: Zap },
];

const PRESET_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  COLLECTION_PRESET_ICONS.map(({ name, Icon }) => [name, Icon]),
);

export function isCustomCollectionIcon(value: string | null | undefined): boolean {
  if (!value) return false;
  const v = value.trim();
  return v.startsWith("data:image") || /^https?:\/\//i.test(v);
}

export function resolveCollectionLucideIcon(name: string): LucideIcon {
  return PRESET_BY_NAME[name] ?? LayoutList;
}
