/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Cms: () => import('#controllers/admin/cms_controller'),
    Content: () => import('#controllers/admin/content_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Media: () => import('#controllers/admin/media_controller'),
    Pages: () => import('#controllers/admin/pages_controller'),
    Permissions: () => import('#controllers/admin/permissions_controller'),
    Plugins: () => import('#controllers/admin/plugins_controller'),
    Roles: () => import('#controllers/admin/roles_controller'),
    Settings: () => import('#controllers/admin/settings_controller'),
    Templates: () => import('#controllers/admin/templates_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  GoogleAuth: () => import('#controllers/google_auth_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PagesPublic: () => import('#controllers/pages_public_controller'),
  PublicCms: () => import('#controllers/public_cms_controller'),
  PublicContent: () => import('#controllers/public_content_controller'),
  Public: () => import('#controllers/public_controller'),
  PublicTemplates: () => import('#controllers/public_templates_controller'),
  Seo: () => import('#controllers/seo_controller'),
  Session: () => import('#controllers/session_controller'),
}
