/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    ApiTokens: () => import('#controllers/admin/api_tokens_controller'),
    Cms: () => import('#controllers/admin/cms_controller'),
    Content: () => import('#controllers/admin/content_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Health: () => import('#controllers/admin/health_controller'),
    MailSettings: () => import('#controllers/admin/mail_settings_controller'),
    Media: () => import('#controllers/admin/media_controller'),
    ModuleInstall: () => import('#controllers/admin/module_install_controller'),
    Modules: () => import('#controllers/admin/modules_controller'),
    Pages: () => import('#controllers/admin/pages_controller'),
    Permissions: () => import('#controllers/admin/permissions_controller'),
    Roles: () => import('#controllers/admin/roles_controller'),
    Schema: () => import('#controllers/admin/schema_controller'),
    Settings: () => import('#controllers/admin/settings_controller'),
    Templates: () => import('#controllers/admin/templates_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  api: {
    v1: {
      CmsRecords: () => import('#controllers/api/v1/cms_records_controller'),
      Content: () => import('#controllers/api/v1/content_controller'),
    },
  },
  GoogleAuth: () => import('#controllers/google_auth_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PagesPublic: () => import('#controllers/pages_public_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  PublicCms: () => import('#controllers/public_cms_controller'),
  PublicContent: () => import('#controllers/public_content_controller'),
  Public: () => import('#controllers/public_controller'),
  PublicTemplates: () => import('#controllers/public_templates_controller'),
  Seo: () => import('#controllers/seo_controller'),
  Session: () => import('#controllers/session_controller'),
}
