/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnnouncementSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'createdByUserId', 'deletedAt', 'id', 'published', 'title', 'updatedAt'] as const
  $columns = AnnouncementSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare published: boolean
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CmsCollectionSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'draftsOn', 'group', 'icon', 'id', 'key', 'label', 'listConfig', 'modelName', 'revisionsOn', 'source', 'tableName', 'updatedAt'] as const
  $columns = CmsCollectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare draftsOn: boolean
  @column()
  declare group: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare label: string
  @column()
  declare listConfig: string
  @column()
  declare modelName: string | null
  @column()
  declare revisionsOn: boolean
  @column()
  declare source: string
  @column()
  declare tableName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CmsFieldSchema extends BaseModel {
  static $columns = ['collectionId', 'config', 'createdAt', 'deletedAt', 'id', 'key', 'label', 'order', 'required', 'type', 'unique', 'updatedAt'] as const
  $columns = CmsFieldSchema.$columns
  @column()
  declare collectionId: string
  @column()
  declare config: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare label: string
  @column()
  declare order: number
  @column()
  declare required: boolean
  @column()
  declare type: string
  @column()
  declare unique: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CmsRevisionSchema extends BaseModel {
  static $columns = ['authorId', 'collectionKey', 'createdAt', 'data', 'deletedAt', 'id', 'recordId', 'status'] as const
  $columns = CmsRevisionSchema.$columns
  @column()
  declare authorId: number | null
  @column()
  declare collectionKey: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare recordId: string
  @column()
  declare status: string
}

export class ContentSchema extends BaseModel {
  static $columns = ['authorId', 'body', 'createdAt', 'deletedAt', 'id', 'slug', 'status', 'title', 'updatedAt'] as const
  $columns = ContentSchema.$columns
  @column()
  declare authorId: number | null
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class IntegrationSettingSchema extends BaseModel {
  static $columns = ['captchaEnabled', 'captchaOnLogin', 'captchaOnRegister', 'captchaProvider', 'captchaSecretEnc', 'captchaSiteKey', 'clarityEnabled', 'clarityProjectId', 'deletedAt', 'ga4Enabled', 'ga4MeasurementId', 'googleAuthEnabled', 'googleClientId', 'googleClientSecretEnc', 'id', 'updatedAt'] as const
  $columns = IntegrationSettingSchema.$columns
  @column()
  declare captchaEnabled: boolean
  @column()
  declare captchaOnLogin: boolean
  @column()
  declare captchaOnRegister: boolean
  @column()
  declare captchaProvider: string | null
  @column()
  declare captchaSecretEnc: string | null
  @column()
  declare captchaSiteKey: string | null
  @column()
  declare clarityEnabled: boolean
  @column()
  declare clarityProjectId: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare ga4Enabled: boolean
  @column()
  declare ga4MeasurementId: string | null
  @column()
  declare googleAuthEnabled: boolean
  @column()
  declare googleClientId: string | null
  @column()
  declare googleClientSecretEnc: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MediaSchema extends BaseModel {
  static $columns = ['authorId', 'createdAt', 'deletedAt', 'filename', 'height', 'id', 'mimeType', 'size', 'url', 'width'] as const
  $columns = MediaSchema.$columns
  @column()
  declare authorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare filename: string
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare size: number
  @column()
  declare url: string
  @column()
  declare width: number | null
}

export class PermissionRoleSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = PermissionRoleSchema.$columns
  @column({ isPrimary: true })
  declare permissionId: string
  @column()
  declare roleId: string
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'isSystem', 'name', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PluginSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'id', 'installedAt', 'name', 'updatedAt', 'version'] as const
  $columns = PluginSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare installedAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: string | null
}

export class RoleUserSchema extends BaseModel {
  static $columns = ['roleId', 'userId'] as const
  $columns = RoleUserSchema.$columns
  @column({ isPrimary: true })
  declare roleId: string
  @column()
  declare userId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'isSystem', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'deletedAt', 'email', 'emailVerifiedAt', 'firstName', 'fullName', 'googleSub', 'id', 'lastName', 'password', 'phone', 'status', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstName: string | null
  @column()
  declare fullName: string | null
  @column()
  declare googleSub: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}

export class WebSettingSchema extends BaseModel {
  static $columns = ['deletedAt', 'id', 'key', 'section', 'updatedAt', 'value'] as const
  $columns = WebSettingSchema.$columns
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare section: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}
