export const BUILTIN_PERMISSIONS: { name: string; description: string }[] = [
  { name: '*', description: 'Wildcard: full access to every resource.' },
  { name: 'content:create', description: 'Create content records.' },
  { name: 'content:read', description: 'Read content records.' },
  { name: 'content:update', description: 'Update content records.' },
  { name: 'content:delete', description: 'Delete content records.' },
  { name: 'user:read', description: 'Read user profiles.' },
  { name: 'user:manage', description: 'Create / update / delete users.' },
  { name: 'media:read', description: 'Read media library files.' },
  { name: 'media:manage', description: 'Upload / delete media files.' },
  { name: 'cms:manage', description: 'Create / edit / delete CMS collection schemas.' },
  { name: 'page:create', description: 'Create builder pages.' },
  { name: 'page:read', description: 'Read builder pages.' },
  { name: 'page:update', description: 'Update builder pages.' },
  { name: 'page:delete', description: 'Delete builder pages.' },
  { name: 'template:create', description: 'Create templates (headers/footers/components/layouts).' },
  { name: 'template:read', description: 'Read templates.' },
  { name: 'template:update', description: 'Update templates.' },
  { name: 'template:delete', description: 'Delete templates.' },
  { name: 'role:manage', description: 'Create / edit / delete roles and assign permissions.' },
  { name: 'permission:manage', description: 'Create / edit / delete permission codes.' },
  { name: 'settings:manage', description: 'Manage site integrations (Google OAuth, CAPTCHA, etc.).' },
  { name: 'plugin:manage', description: 'Enable / disable installed plugins.' },
]

export const BUILTIN_ROLES: { name: string; description: string }[] = [
  { name: 'SUPERADMIN', description: 'Full access. Automatically granted the * wildcard.' },
  { name: 'ADMIN', description: 'Operational admin — manages content and users.' },
  { name: 'USER', description: 'Default signed-in user.' },
  { name: 'GUEST', description: 'Unauthenticated / public viewer.' },
]

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  SUPERADMIN: ['*'],
  ADMIN: [
    'content:create',
    'content:read',
    'content:update',
    'content:delete',
    'user:read',
    'user:manage',
    'media:read',
    'media:manage',
    'cms:manage',
    'page:create',
    'page:read',
    'page:update',
    'page:delete',
    'template:create',
    'template:read',
    'template:update',
    'template:delete',
    'settings:manage',
    'plugin:manage',
  ],
  USER: ['content:create', 'content:read', 'content:update', 'content:delete'],
  GUEST: ['content:read'],
}
