import app from '@adonisjs/core/services/app'
import { defineConfig } from '@adonisjs/vite'

const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this
   * directory. The path should be relative from
   * the application root.
   */
  buildDirectory: 'public/assets',

  /**
   * The path to the manifest file generated by the
   * "vite build" command.
   *
   * Absolute on purpose. `@adonisjs/vite` checks this path with a plain
   * `existsSync`, i.e. relative to the *working directory*, not the app root.
   * `npm start` runs `node current/bin/server.js` from the repo root, where
   * `public/assets` is empty (the release lives under `releases/…`), so a
   * relative path made every page 500 with "Missing manifest file" unless the
   * process happened to be started from inside the release.
   */
  manifestFile: app.makePath('public/assets/.vite/manifest.json'),

  /**
   * Feel free to change the value of the "assetsUrl" to
   * point to a CDN in production.
   */
  assetsUrl: '/assets',

  /**
   * HTML attributes added to generated script tags.
   */
  scriptAttributes: {
    /**
     * Execute scripts after HTML parsing is complete.
     */
    defer: true,
  },
})

export default viteBackendConfig
