/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'public.post': {
    methods: ["GET","HEAD"],
    pattern: '/posts/:slug',
    tokens: [{"old":"/posts/:slug","type":0,"val":"posts","end":""},{"old":"/posts/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public.post']['types'],
  },
  'public.offline': {
    methods: ["GET","HEAD"],
    pattern: '/offline',
    tokens: [{"old":"/offline","type":0,"val":"offline","end":""}],
    types: placeholder as Registry['public.offline']['types'],
  },
  'public_content.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/public/content',
    tokens: [{"old":"/api/public/content","type":0,"val":"api","end":""},{"old":"/api/public/content","type":0,"val":"public","end":""},{"old":"/api/public/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['public_content.index']['types'],
  },
  'public_content.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/public/content/:slug',
    tokens: [{"old":"/api/public/content/:slug","type":0,"val":"api","end":""},{"old":"/api/public/content/:slug","type":0,"val":"public","end":""},{"old":"/api/public/content/:slug","type":0,"val":"content","end":""},{"old":"/api/public/content/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public_content.show']['types'],
  },
  'public_cms.records': {
    methods: ["GET","HEAD"],
    pattern: '/api/public/cms/:key/records',
    tokens: [{"old":"/api/public/cms/:key/records","type":0,"val":"api","end":""},{"old":"/api/public/cms/:key/records","type":0,"val":"public","end":""},{"old":"/api/public/cms/:key/records","type":0,"val":"cms","end":""},{"old":"/api/public/cms/:key/records","type":1,"val":"key","end":""},{"old":"/api/public/cms/:key/records","type":0,"val":"records","end":""}],
    types: placeholder as Registry['public_cms.records']['types'],
  },
  'public_cms.record': {
    methods: ["GET","HEAD"],
    pattern: '/api/public/cms/:key/records/:id',
    tokens: [{"old":"/api/public/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/public/cms/:key/records/:id","type":0,"val":"public","end":""},{"old":"/api/public/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/public/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/public/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/public/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['public_cms.record']['types'],
  },
  'public_templates.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/public/templates/:id',
    tokens: [{"old":"/api/public/templates/:id","type":0,"val":"api","end":""},{"old":"/api/public/templates/:id","type":0,"val":"public","end":""},{"old":"/api/public/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/public/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['public_templates.show']['types'],
  },
  'seo.robots': {
    methods: ["GET","HEAD"],
    pattern: '/robots.txt',
    tokens: [{"old":"/robots.txt","type":0,"val":"robots.txt","end":""}],
    types: placeholder as Registry['seo.robots']['types'],
  },
  'seo.sitemap': {
    methods: ["GET","HEAD"],
    pattern: '/sitemap.xml',
    tokens: [{"old":"/sitemap.xml","type":0,"val":"sitemap.xml","end":""}],
    types: placeholder as Registry['seo.sitemap']['types'],
  },
  'settings.get_auth_config': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/config',
    tokens: [{"old":"/api/auth/config","type":0,"val":"api","end":""},{"old":"/api/auth/config","type":0,"val":"auth","end":""},{"old":"/api/auth/config","type":0,"val":"config","end":""}],
    types: placeholder as Registry['settings.get_auth_config']['types'],
  },
  'google_auth.status': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/status',
    tokens: [{"old":"/auth/google/status","type":0,"val":"auth","end":""},{"old":"/auth/google/status","type":0,"val":"google","end":""},{"old":"/auth/google/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['google_auth.status']['types'],
  },
  'google_auth.start': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google',
    tokens: [{"old":"/auth/google","type":0,"val":"auth","end":""},{"old":"/auth/google","type":0,"val":"google","end":""}],
    types: placeholder as Registry['google_auth.start']['types'],
  },
  'google_auth.callback': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/callback',
    tokens: [{"old":"/auth/google/callback","type":0,"val":"auth","end":""},{"old":"/auth/google/callback","type":0,"val":"google","end":""},{"old":"/auth/google/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['google_auth.callback']['types'],
  },
  'new_account.create': {
    methods: ["GET","HEAD"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['new_account.create']['types'],
  },
  'new_account.store': {
    methods: ["POST"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['new_account.store']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'legacy.signup.store': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['legacy.signup.store']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'session.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/me',
    tokens: [{"old":"/api/me","type":0,"val":"api","end":""},{"old":"/api/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['session.me']['types'],
  },
  'session.update_profile': {
    methods: ["PUT"],
    pattern: '/api/me',
    tokens: [{"old":"/api/me","type":0,"val":"api","end":""},{"old":"/api/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['session.update_profile']['types'],
  },
  'dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/dashboard',
    tokens: [{"old":"/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.index']['types'],
  },
  'dashboard.analytics_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/analytics',
    tokens: [{"old":"/admin/analytics","type":0,"val":"admin","end":""},{"old":"/admin/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['dashboard.analytics_page']['types'],
  },
  'dashboard.profile_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/profile',
    tokens: [{"old":"/admin/profile","type":0,"val":"admin","end":""},{"old":"/admin/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['dashboard.profile_page']['types'],
  },
  'users.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.page']['types'],
  },
  'users.generate_password': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/users/generate-password',
    tokens: [{"old":"/api/admin/users/generate-password","type":0,"val":"api","end":""},{"old":"/api/admin/users/generate-password","type":0,"val":"admin","end":""},{"old":"/api/admin/users/generate-password","type":0,"val":"users","end":""},{"old":"/api/admin/users/generate-password","type":0,"val":"generate-password","end":""}],
    types: placeholder as Registry['users.generate_password']['types'],
  },
  'users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/users',
    tokens: [{"old":"/api/admin/users","type":0,"val":"api","end":""},{"old":"/api/admin/users","type":0,"val":"admin","end":""},{"old":"/api/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.index']['types'],
  },
  'users.trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/users/trash',
    tokens: [{"old":"/api/admin/users/trash","type":0,"val":"api","end":""},{"old":"/api/admin/users/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/users/trash","type":0,"val":"users","end":""},{"old":"/api/admin/users/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['users.trash']['types'],
  },
  'users.store': {
    methods: ["POST"],
    pattern: '/api/admin/users',
    tokens: [{"old":"/api/admin/users","type":0,"val":"api","end":""},{"old":"/api/admin/users","type":0,"val":"admin","end":""},{"old":"/api/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.store']['types'],
  },
  'users.restore': {
    methods: ["POST"],
    pattern: '/api/admin/users/:id/restore',
    tokens: [{"old":"/api/admin/users/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/restore","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['users.restore']['types'],
  },
  'users.force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/users/:id/force',
    tokens: [{"old":"/api/admin/users/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/force","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['users.force_destroy']['types'],
  },
  'users.update': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id',
    tokens: [{"old":"/api/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/users/:id',
    tokens: [{"old":"/api/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.destroy']['types'],
  },
  'roles.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.page']['types'],
  },
  'roles.new_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/new',
    tokens: [{"old":"/admin/roles/new","type":0,"val":"admin","end":""},{"old":"/admin/roles/new","type":0,"val":"roles","end":""},{"old":"/admin/roles/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['roles.new_page']['types'],
  },
  'roles.detail_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.detail_page']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/roles',
    tokens: [{"old":"/api/admin/roles","type":0,"val":"api","end":""},{"old":"/api/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/roles/trash',
    tokens: [{"old":"/api/admin/roles/trash","type":0,"val":"api","end":""},{"old":"/api/admin/roles/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/roles/trash","type":0,"val":"roles","end":""},{"old":"/api/admin/roles/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['roles.trash']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/roles/:id',
    tokens: [{"old":"/api/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/api/admin/roles',
    tokens: [{"old":"/api/admin/roles","type":0,"val":"api","end":""},{"old":"/api/admin/roles","type":0,"val":"admin","end":""},{"old":"/api/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.restore': {
    methods: ["POST"],
    pattern: '/api/admin/roles/:id/restore',
    tokens: [{"old":"/api/admin/roles/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/roles/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/roles/:id/restore","type":0,"val":"roles","end":""},{"old":"/api/admin/roles/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/roles/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['roles.restore']['types'],
  },
  'roles.force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/roles/:id/force',
    tokens: [{"old":"/api/admin/roles/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/roles/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/roles/:id/force","type":0,"val":"roles","end":""},{"old":"/api/admin/roles/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/roles/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['roles.force_destroy']['types'],
  },
  'roles.update': {
    methods: ["PUT"],
    pattern: '/api/admin/roles/:id',
    tokens: [{"old":"/api/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/roles/:id',
    tokens: [{"old":"/api/admin/roles/:id","type":0,"val":"api","end":""},{"old":"/api/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'permissions.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions',
    tokens: [{"old":"/admin/permissions","type":0,"val":"admin","end":""},{"old":"/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['permissions.page']['types'],
  },
  'permissions.new_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions/new',
    tokens: [{"old":"/admin/permissions/new","type":0,"val":"admin","end":""},{"old":"/admin/permissions/new","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['permissions.new_page']['types'],
  },
  'permissions.detail_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/permissions/:id',
    tokens: [{"old":"/admin/permissions/:id","type":0,"val":"admin","end":""},{"old":"/admin/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/admin/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.detail_page']['types'],
  },
  'permissions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/permissions',
    tokens: [{"old":"/api/admin/permissions","type":0,"val":"api","end":""},{"old":"/api/admin/permissions","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['permissions.index']['types'],
  },
  'permissions.trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/permissions/trash',
    tokens: [{"old":"/api/admin/permissions/trash","type":0,"val":"api","end":""},{"old":"/api/admin/permissions/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions/trash","type":0,"val":"permissions","end":""},{"old":"/api/admin/permissions/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['permissions.trash']['types'],
  },
  'permissions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/permissions/:id',
    tokens: [{"old":"/api/admin/permissions/:id","type":0,"val":"api","end":""},{"old":"/api/admin/permissions/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/api/admin/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.show']['types'],
  },
  'permissions.store': {
    methods: ["POST"],
    pattern: '/api/admin/permissions',
    tokens: [{"old":"/api/admin/permissions","type":0,"val":"api","end":""},{"old":"/api/admin/permissions","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['permissions.store']['types'],
  },
  'permissions.restore': {
    methods: ["POST"],
    pattern: '/api/admin/permissions/:id/restore',
    tokens: [{"old":"/api/admin/permissions/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/permissions/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions/:id/restore","type":0,"val":"permissions","end":""},{"old":"/api/admin/permissions/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/permissions/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['permissions.restore']['types'],
  },
  'permissions.force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/permissions/:id/force',
    tokens: [{"old":"/api/admin/permissions/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/permissions/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions/:id/force","type":0,"val":"permissions","end":""},{"old":"/api/admin/permissions/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/permissions/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['permissions.force_destroy']['types'],
  },
  'permissions.update': {
    methods: ["PUT"],
    pattern: '/api/admin/permissions/:id',
    tokens: [{"old":"/api/admin/permissions/:id","type":0,"val":"api","end":""},{"old":"/api/admin/permissions/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/api/admin/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.update']['types'],
  },
  'permissions.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/permissions/:id',
    tokens: [{"old":"/api/admin/permissions/:id","type":0,"val":"api","end":""},{"old":"/api/admin/permissions/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/api/admin/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.destroy']['types'],
  },
  'content.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content',
    tokens: [{"old":"/admin/content","type":0,"val":"admin","end":""},{"old":"/admin/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['content.page']['types'],
  },
  'content.new_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/new',
    tokens: [{"old":"/admin/content/new","type":0,"val":"admin","end":""},{"old":"/admin/content/new","type":0,"val":"content","end":""},{"old":"/admin/content/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['content.new_page']['types'],
  },
  'content.edit_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/:id/edit',
    tokens: [{"old":"/admin/content/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/content/:id/edit","type":0,"val":"content","end":""},{"old":"/admin/content/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/content/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['content.edit_page']['types'],
  },
  'content.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/content',
    tokens: [{"old":"/api/admin/content","type":0,"val":"api","end":""},{"old":"/api/admin/content","type":0,"val":"admin","end":""},{"old":"/api/admin/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['content.index']['types'],
  },
  'content.trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/content/trash',
    tokens: [{"old":"/api/admin/content/trash","type":0,"val":"api","end":""},{"old":"/api/admin/content/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/content/trash","type":0,"val":"content","end":""},{"old":"/api/admin/content/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['content.trash']['types'],
  },
  'content.check_slug': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/content/check-slug',
    tokens: [{"old":"/api/admin/content/check-slug","type":0,"val":"api","end":""},{"old":"/api/admin/content/check-slug","type":0,"val":"admin","end":""},{"old":"/api/admin/content/check-slug","type":0,"val":"content","end":""},{"old":"/api/admin/content/check-slug","type":0,"val":"check-slug","end":""}],
    types: placeholder as Registry['content.check_slug']['types'],
  },
  'content.store': {
    methods: ["POST"],
    pattern: '/api/admin/content',
    tokens: [{"old":"/api/admin/content","type":0,"val":"api","end":""},{"old":"/api/admin/content","type":0,"val":"admin","end":""},{"old":"/api/admin/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['content.store']['types'],
  },
  'content.restore': {
    methods: ["POST"],
    pattern: '/api/admin/content/:id/restore',
    tokens: [{"old":"/api/admin/content/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/content/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/content/:id/restore","type":0,"val":"content","end":""},{"old":"/api/admin/content/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/content/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['content.restore']['types'],
  },
  'content.force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/content/:id/force',
    tokens: [{"old":"/api/admin/content/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/content/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/content/:id/force","type":0,"val":"content","end":""},{"old":"/api/admin/content/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/content/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['content.force_destroy']['types'],
  },
  'content.update': {
    methods: ["PUT"],
    pattern: '/api/admin/content/:id',
    tokens: [{"old":"/api/admin/content/:id","type":0,"val":"api","end":""},{"old":"/api/admin/content/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/content/:id","type":0,"val":"content","end":""},{"old":"/api/admin/content/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['content.update']['types'],
  },
  'content.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/content/:id',
    tokens: [{"old":"/api/admin/content/:id","type":0,"val":"api","end":""},{"old":"/api/admin/content/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/content/:id","type":0,"val":"content","end":""},{"old":"/api/admin/content/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['content.destroy']['types'],
  },
  'pages.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages',
    tokens: [{"old":"/admin/pages","type":0,"val":"admin","end":""},{"old":"/admin/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['pages.page']['types'],
  },
  'pages.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/edit',
    tokens: [{"old":"/admin/pages/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/edit","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['pages.edit']['types'],
  },
  'pages_public.preview': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/preview',
    tokens: [{"old":"/admin/pages/:id/preview","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/preview","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/preview","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['pages_public.preview']['types'],
  },
  'pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/pages',
    tokens: [{"old":"/api/admin/pages","type":0,"val":"api","end":""},{"old":"/api/admin/pages","type":0,"val":"admin","end":""},{"old":"/api/admin/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['pages.index']['types'],
  },
  'pages.trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/pages/trash',
    tokens: [{"old":"/api/admin/pages/trash","type":0,"val":"api","end":""},{"old":"/api/admin/pages/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/trash","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['pages.trash']['types'],
  },
  'pages.collections': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/pages/collections',
    tokens: [{"old":"/api/admin/pages/collections","type":0,"val":"api","end":""},{"old":"/api/admin/pages/collections","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/collections","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['pages.collections']['types'],
  },
  'pages.store': {
    methods: ["POST"],
    pattern: '/api/admin/pages',
    tokens: [{"old":"/api/admin/pages","type":0,"val":"api","end":""},{"old":"/api/admin/pages","type":0,"val":"admin","end":""},{"old":"/api/admin/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['pages.store']['types'],
  },
  'pages.restore': {
    methods: ["POST"],
    pattern: '/api/admin/pages/:id/restore',
    tokens: [{"old":"/api/admin/pages/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id/restore","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/pages/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['pages.restore']['types'],
  },
  'pages.force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/pages/:id/force',
    tokens: [{"old":"/api/admin/pages/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id/force","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/pages/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['pages.force_destroy']['types'],
  },
  'pages.revisions': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/pages/:id/revisions',
    tokens: [{"old":"/api/admin/pages/:id/revisions","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id/revisions","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id/revisions","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id/revisions","type":1,"val":"id","end":""},{"old":"/api/admin/pages/:id/revisions","type":0,"val":"revisions","end":""}],
    types: placeholder as Registry['pages.revisions']['types'],
  },
  'pages.restore_revision': {
    methods: ["POST"],
    pattern: '/api/admin/pages/:id/revisions/:revisionId/restore',
    tokens: [{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":1,"val":"id","end":""},{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":0,"val":"revisions","end":""},{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":1,"val":"revisionId","end":""},{"old":"/api/admin/pages/:id/revisions/:revisionId/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['pages.restore_revision']['types'],
  },
  'pages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/pages/:id',
    tokens: [{"old":"/api/admin/pages/:id","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pages.show']['types'],
  },
  'pages.update': {
    methods: ["PUT"],
    pattern: '/api/admin/pages/:id',
    tokens: [{"old":"/api/admin/pages/:id","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pages.update']['types'],
  },
  'pages.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/pages/:id',
    tokens: [{"old":"/api/admin/pages/:id","type":0,"val":"api","end":""},{"old":"/api/admin/pages/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/pages/:id","type":0,"val":"pages","end":""},{"old":"/api/admin/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pages.destroy']['types'],
  },
  'templates.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/templates',
    tokens: [{"old":"/admin/templates","type":0,"val":"admin","end":""},{"old":"/admin/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.page']['types'],
  },
  'templates.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/templates/:id/edit',
    tokens: [{"old":"/admin/templates/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/templates/:id/edit","type":0,"val":"templates","end":""},{"old":"/admin/templates/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/templates/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['templates.edit']['types'],
  },
  'templates.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/templates',
    tokens: [{"old":"/api/admin/templates","type":0,"val":"api","end":""},{"old":"/api/admin/templates","type":0,"val":"admin","end":""},{"old":"/api/admin/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.index']['types'],
  },
  'templates.store': {
    methods: ["POST"],
    pattern: '/api/admin/templates',
    tokens: [{"old":"/api/admin/templates","type":0,"val":"api","end":""},{"old":"/api/admin/templates","type":0,"val":"admin","end":""},{"old":"/api/admin/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.store']['types'],
  },
  'templates.duplicate': {
    methods: ["POST"],
    pattern: '/api/admin/templates/:id/duplicate',
    tokens: [{"old":"/api/admin/templates/:id/duplicate","type":0,"val":"api","end":""},{"old":"/api/admin/templates/:id/duplicate","type":0,"val":"admin","end":""},{"old":"/api/admin/templates/:id/duplicate","type":0,"val":"templates","end":""},{"old":"/api/admin/templates/:id/duplicate","type":1,"val":"id","end":""},{"old":"/api/admin/templates/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['templates.duplicate']['types'],
  },
  'templates.set_default': {
    methods: ["POST"],
    pattern: '/api/admin/templates/:id/default',
    tokens: [{"old":"/api/admin/templates/:id/default","type":0,"val":"api","end":""},{"old":"/api/admin/templates/:id/default","type":0,"val":"admin","end":""},{"old":"/api/admin/templates/:id/default","type":0,"val":"templates","end":""},{"old":"/api/admin/templates/:id/default","type":1,"val":"id","end":""},{"old":"/api/admin/templates/:id/default","type":0,"val":"default","end":""}],
    types: placeholder as Registry['templates.set_default']['types'],
  },
  'templates.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/templates/:id',
    tokens: [{"old":"/api/admin/templates/:id","type":0,"val":"api","end":""},{"old":"/api/admin/templates/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/admin/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templates.show']['types'],
  },
  'templates.update': {
    methods: ["PUT"],
    pattern: '/api/admin/templates/:id',
    tokens: [{"old":"/api/admin/templates/:id","type":0,"val":"api","end":""},{"old":"/api/admin/templates/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/admin/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templates.update']['types'],
  },
  'templates.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/templates/:id',
    tokens: [{"old":"/api/admin/templates/:id","type":0,"val":"api","end":""},{"old":"/api/admin/templates/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/admin/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templates.destroy']['types'],
  },
  'cms.collections_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/collections',
    tokens: [{"old":"/admin/cms/collections","type":0,"val":"admin","end":""},{"old":"/admin/cms/collections","type":0,"val":"cms","end":""},{"old":"/admin/cms/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['cms.collections_page']['types'],
  },
  'cms.collections_new_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/collections/new',
    tokens: [{"old":"/admin/cms/collections/new","type":0,"val":"admin","end":""},{"old":"/admin/cms/collections/new","type":0,"val":"cms","end":""},{"old":"/admin/cms/collections/new","type":0,"val":"collections","end":""},{"old":"/admin/cms/collections/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['cms.collections_new_page']['types'],
  },
  'cms.collection_detail_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/collections/:key',
    tokens: [{"old":"/admin/cms/collections/:key","type":0,"val":"admin","end":""},{"old":"/admin/cms/collections/:key","type":0,"val":"cms","end":""},{"old":"/admin/cms/collections/:key","type":0,"val":"collections","end":""},{"old":"/admin/cms/collections/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.collection_detail_page']['types'],
  },
  'cms.collections_index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/collections',
    tokens: [{"old":"/api/admin/cms/collections","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['cms.collections_index']['types'],
  },
  'cms.collections_trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/collections/trash',
    tokens: [{"old":"/api/admin/cms/collections/trash","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/trash","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/trash","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['cms.collections_trash']['types'],
  },
  'cms.collections_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/collections/:key',
    tokens: [{"old":"/api/admin/cms/collections/:key","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.collections_show']['types'],
  },
  'cms.collections_store': {
    methods: ["POST"],
    pattern: '/api/admin/cms/collections',
    tokens: [{"old":"/api/admin/cms/collections","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['cms.collections_store']['types'],
  },
  'cms.collections_restore': {
    methods: ["POST"],
    pattern: '/api/admin/cms/collections/:key/restore',
    tokens: [{"old":"/api/admin/cms/collections/:key/restore","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key/restore","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key/restore","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key/restore","type":1,"val":"key","end":""},{"old":"/api/admin/cms/collections/:key/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['cms.collections_restore']['types'],
  },
  'cms.collections_force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/cms/collections/:key/force',
    tokens: [{"old":"/api/admin/cms/collections/:key/force","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key/force","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key/force","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key/force","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key/force","type":1,"val":"key","end":""},{"old":"/api/admin/cms/collections/:key/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['cms.collections_force_destroy']['types'],
  },
  'cms.collections_update': {
    methods: ["PUT"],
    pattern: '/api/admin/cms/collections/:key',
    tokens: [{"old":"/api/admin/cms/collections/:key","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.collections_update']['types'],
  },
  'cms.collections_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/cms/collections/:key',
    tokens: [{"old":"/api/admin/cms/collections/:key","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.collections_destroy']['types'],
  },
  'cms.fields_store': {
    methods: ["POST"],
    pattern: '/api/admin/cms/collections/:key/fields',
    tokens: [{"old":"/api/admin/cms/collections/:key/fields","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key/fields","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key/fields","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key/fields","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key/fields","type":1,"val":"key","end":""},{"old":"/api/admin/cms/collections/:key/fields","type":0,"val":"fields","end":""}],
    types: placeholder as Registry['cms.fields_store']['types'],
  },
  'cms.fields_update': {
    methods: ["PUT"],
    pattern: '/api/admin/cms/collections/:key/fields/:fieldKey',
    tokens: [{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":1,"val":"key","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"fields","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":1,"val":"fieldKey","end":""}],
    types: placeholder as Registry['cms.fields_update']['types'],
  },
  'cms.fields_reorder': {
    methods: ["PATCH"],
    pattern: '/api/admin/cms/collections/:key/fields/reorder',
    tokens: [{"old":"/api/admin/cms/collections/:key/fields/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key/fields/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key/fields/reorder","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key/fields/reorder","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key/fields/reorder","type":1,"val":"key","end":""},{"old":"/api/admin/cms/collections/:key/fields/reorder","type":0,"val":"fields","end":""},{"old":"/api/admin/cms/collections/:key/fields/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['cms.fields_reorder']['types'],
  },
  'cms.fields_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/cms/collections/:key/fields/:fieldKey',
    tokens: [{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"api","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"collections","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":1,"val":"key","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":0,"val":"fields","end":""},{"old":"/api/admin/cms/collections/:key/fields/:fieldKey","type":1,"val":"fieldKey","end":""}],
    types: placeholder as Registry['cms.fields_destroy']['types'],
  },
  'cms.components_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/components',
    tokens: [{"old":"/admin/cms/components","type":0,"val":"admin","end":""},{"old":"/admin/cms/components","type":0,"val":"cms","end":""},{"old":"/admin/cms/components","type":0,"val":"components","end":""}],
    types: placeholder as Registry['cms.components_page']['types'],
  },
  'cms.components_index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/components',
    tokens: [{"old":"/api/admin/cms/components","type":0,"val":"api","end":""},{"old":"/api/admin/cms/components","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/components","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/components","type":0,"val":"components","end":""}],
    types: placeholder as Registry['cms.components_index']['types'],
  },
  'cms.components_store': {
    methods: ["POST"],
    pattern: '/api/admin/cms/components',
    tokens: [{"old":"/api/admin/cms/components","type":0,"val":"api","end":""},{"old":"/api/admin/cms/components","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/components","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/components","type":0,"val":"components","end":""}],
    types: placeholder as Registry['cms.components_store']['types'],
  },
  'cms.components_update': {
    methods: ["PUT"],
    pattern: '/api/admin/cms/components/:key',
    tokens: [{"old":"/api/admin/cms/components/:key","type":0,"val":"api","end":""},{"old":"/api/admin/cms/components/:key","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/components/:key","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/components/:key","type":0,"val":"components","end":""},{"old":"/api/admin/cms/components/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.components_update']['types'],
  },
  'cms.components_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/cms/components/:key',
    tokens: [{"old":"/api/admin/cms/components/:key","type":0,"val":"api","end":""},{"old":"/api/admin/cms/components/:key","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/components/:key","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/components/:key","type":0,"val":"components","end":""},{"old":"/api/admin/cms/components/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.components_destroy']['types'],
  },
  'cms.records_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/:key',
    tokens: [{"old":"/admin/cms/:key","type":0,"val":"admin","end":""},{"old":"/admin/cms/:key","type":0,"val":"cms","end":""},{"old":"/admin/cms/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['cms.records_page']['types'],
  },
  'cms.new_record_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/:key/new',
    tokens: [{"old":"/admin/cms/:key/new","type":0,"val":"admin","end":""},{"old":"/admin/cms/:key/new","type":0,"val":"cms","end":""},{"old":"/admin/cms/:key/new","type":1,"val":"key","end":""},{"old":"/admin/cms/:key/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['cms.new_record_page']['types'],
  },
  'cms.record_detail_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/cms/:key/:id',
    tokens: [{"old":"/admin/cms/:key/:id","type":0,"val":"admin","end":""},{"old":"/admin/cms/:key/:id","type":0,"val":"cms","end":""},{"old":"/admin/cms/:key/:id","type":1,"val":"key","end":""},{"old":"/admin/cms/:key/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms.record_detail_page']['types'],
  },
  'cms.records_index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/:key/records',
    tokens: [{"old":"/api/admin/cms/:key/records","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records","type":0,"val":"records","end":""}],
    types: placeholder as Registry['cms.records_index']['types'],
  },
  'cms.records_trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/:key/records/trash',
    tokens: [{"old":"/api/admin/cms/:key/records/trash","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/trash","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/trash","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/trash","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['cms.records_trash']['types'],
  },
  'cms.records_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/:key/records/:id',
    tokens: [{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms.records_show']['types'],
  },
  'cms.records_store': {
    methods: ["POST"],
    pattern: '/api/admin/cms/:key/records',
    tokens: [{"old":"/api/admin/cms/:key/records","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records","type":0,"val":"records","end":""}],
    types: placeholder as Registry['cms.records_store']['types'],
  },
  'cms.records_restore': {
    methods: ["POST"],
    pattern: '/api/admin/cms/:key/records/:id/restore',
    tokens: [{"old":"/api/admin/cms/:key/records/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id/restore","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id/restore","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id/restore","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/cms/:key/records/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['cms.records_restore']['types'],
  },
  'cms.records_force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/cms/:key/records/:id/force',
    tokens: [{"old":"/api/admin/cms/:key/records/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id/force","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id/force","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id/force","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/cms/:key/records/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['cms.records_force_destroy']['types'],
  },
  'cms.records_update': {
    methods: ["PUT"],
    pattern: '/api/admin/cms/:key/records/:id',
    tokens: [{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms.records_update']['types'],
  },
  'cms.records_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/cms/:key/records/:id',
    tokens: [{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms.records_destroy']['types'],
  },
  'cms.revisions_index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cms/:key/records/:id/revisions',
    tokens: [{"old":"/api/admin/cms/:key/records/:id/revisions","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions","type":1,"val":"id","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions","type":0,"val":"revisions","end":""}],
    types: placeholder as Registry['cms.revisions_index']['types'],
  },
  'cms.revisions_restore': {
    methods: ["POST"],
    pattern: '/api/admin/cms/:key/records/:id/revisions/:revisionId/restore',
    tokens: [{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":0,"val":"api","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":0,"val":"cms","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":1,"val":"key","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":0,"val":"records","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":1,"val":"id","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":0,"val":"revisions","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":1,"val":"revisionId","end":""},{"old":"/api/admin/cms/:key/records/:id/revisions/:revisionId/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['cms.revisions_restore']['types'],
  },
  'media.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/media',
    tokens: [{"old":"/admin/media","type":0,"val":"admin","end":""},{"old":"/admin/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media.page']['types'],
  },
  'media.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/media',
    tokens: [{"old":"/api/admin/media","type":0,"val":"api","end":""},{"old":"/api/admin/media","type":0,"val":"admin","end":""},{"old":"/api/admin/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media.index']['types'],
  },
  'media.trash': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/media/trash',
    tokens: [{"old":"/api/admin/media/trash","type":0,"val":"api","end":""},{"old":"/api/admin/media/trash","type":0,"val":"admin","end":""},{"old":"/api/admin/media/trash","type":0,"val":"media","end":""},{"old":"/api/admin/media/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['media.trash']['types'],
  },
  'media.store': {
    methods: ["POST"],
    pattern: '/api/admin/media',
    tokens: [{"old":"/api/admin/media","type":0,"val":"api","end":""},{"old":"/api/admin/media","type":0,"val":"admin","end":""},{"old":"/api/admin/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media.store']['types'],
  },
  'media.replace': {
    methods: ["POST"],
    pattern: '/api/admin/media/:id/file',
    tokens: [{"old":"/api/admin/media/:id/file","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id/file","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id/file","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id/file","type":1,"val":"id","end":""},{"old":"/api/admin/media/:id/file","type":0,"val":"file","end":""}],
    types: placeholder as Registry['media.replace']['types'],
  },
  'media.update': {
    methods: ["PATCH"],
    pattern: '/api/admin/media/:id',
    tokens: [{"old":"/api/admin/media/:id","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media.update']['types'],
  },
  'media.restore': {
    methods: ["POST"],
    pattern: '/api/admin/media/:id/restore',
    tokens: [{"old":"/api/admin/media/:id/restore","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id/restore","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id/restore","type":1,"val":"id","end":""},{"old":"/api/admin/media/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['media.restore']['types'],
  },
  'media.force_destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/media/:id/force',
    tokens: [{"old":"/api/admin/media/:id/force","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id/force","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id/force","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id/force","type":1,"val":"id","end":""},{"old":"/api/admin/media/:id/force","type":0,"val":"force","end":""}],
    types: placeholder as Registry['media.force_destroy']['types'],
  },
  'media.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/media/:id',
    tokens: [{"old":"/api/admin/media/:id","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media.destroy']['types'],
  },
  'settings.settings_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings',
    tokens: [{"old":"/admin/settings","type":0,"val":"admin","end":""},{"old":"/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.settings_page']['types'],
  },
  'settings.website_settings_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/website-settings',
    tokens: [{"old":"/admin/website-settings","type":0,"val":"admin","end":""},{"old":"/admin/website-settings","type":0,"val":"website-settings","end":""}],
    types: placeholder as Registry['settings.website_settings_page']['types'],
  },
  'settings.application_settings_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/application',
    tokens: [{"old":"/admin/settings/application","type":0,"val":"admin","end":""},{"old":"/admin/settings/application","type":0,"val":"settings","end":""},{"old":"/admin/settings/application","type":0,"val":"application","end":""}],
    types: placeholder as Registry['settings.application_settings_page']['types'],
  },
  'settings.integrations_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/integrations',
    tokens: [{"old":"/admin/integrations","type":0,"val":"admin","end":""},{"old":"/admin/integrations","type":0,"val":"integrations","end":""}],
    types: placeholder as Registry['settings.integrations_page']['types'],
  },
  'settings.integrations_google_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/integrations/google',
    tokens: [{"old":"/admin/integrations/google","type":0,"val":"admin","end":""},{"old":"/admin/integrations/google","type":0,"val":"integrations","end":""},{"old":"/admin/integrations/google","type":0,"val":"google","end":""}],
    types: placeholder as Registry['settings.integrations_google_page']['types'],
  },
  'settings.integrations_captcha_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/integrations/captcha',
    tokens: [{"old":"/admin/integrations/captcha","type":0,"val":"admin","end":""},{"old":"/admin/integrations/captcha","type":0,"val":"integrations","end":""},{"old":"/admin/integrations/captcha","type":0,"val":"captcha","end":""}],
    types: placeholder as Registry['settings.integrations_captcha_page']['types'],
  },
  'settings.integrations_ga_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/integrations/google-analytics',
    tokens: [{"old":"/admin/integrations/google-analytics","type":0,"val":"admin","end":""},{"old":"/admin/integrations/google-analytics","type":0,"val":"integrations","end":""},{"old":"/admin/integrations/google-analytics","type":0,"val":"google-analytics","end":""}],
    types: placeholder as Registry['settings.integrations_ga_page']['types'],
  },
  'settings.integrations_clarity_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/integrations/clarity',
    tokens: [{"old":"/admin/integrations/clarity","type":0,"val":"admin","end":""},{"old":"/admin/integrations/clarity","type":0,"val":"integrations","end":""},{"old":"/admin/integrations/clarity","type":0,"val":"clarity","end":""}],
    types: placeholder as Registry['settings.integrations_clarity_page']['types'],
  },
  'settings.get_web_settings': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/settings/web',
    tokens: [{"old":"/api/admin/settings/web","type":0,"val":"api","end":""},{"old":"/api/admin/settings/web","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/web","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/web","type":0,"val":"web","end":""}],
    types: placeholder as Registry['settings.get_web_settings']['types'],
  },
  'settings.update_web_settings': {
    methods: ["PUT"],
    pattern: '/api/admin/settings/web',
    tokens: [{"old":"/api/admin/settings/web","type":0,"val":"api","end":""},{"old":"/api/admin/settings/web","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/web","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/web","type":0,"val":"web","end":""}],
    types: placeholder as Registry['settings.update_web_settings']['types'],
  },
  'settings.get_integration_settings': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/settings/integrations',
    tokens: [{"old":"/api/admin/settings/integrations","type":0,"val":"api","end":""},{"old":"/api/admin/settings/integrations","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/integrations","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/integrations","type":0,"val":"integrations","end":""}],
    types: placeholder as Registry['settings.get_integration_settings']['types'],
  },
  'settings.update_integration_settings': {
    methods: ["PUT"],
    pattern: '/api/admin/settings/integrations',
    tokens: [{"old":"/api/admin/settings/integrations","type":0,"val":"api","end":""},{"old":"/api/admin/settings/integrations","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/integrations","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/integrations","type":0,"val":"integrations","end":""}],
    types: placeholder as Registry['settings.update_integration_settings']['types'],
  },
  'settings.get_page_code': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/settings/page-code',
    tokens: [{"old":"/api/admin/settings/page-code","type":0,"val":"api","end":""},{"old":"/api/admin/settings/page-code","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/page-code","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/page-code","type":0,"val":"page-code","end":""}],
    types: placeholder as Registry['settings.get_page_code']['types'],
  },
  'settings.update_page_code': {
    methods: ["PUT"],
    pattern: '/api/admin/settings/page-code',
    tokens: [{"old":"/api/admin/settings/page-code","type":0,"val":"api","end":""},{"old":"/api/admin/settings/page-code","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/page-code","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/page-code","type":0,"val":"page-code","end":""}],
    types: placeholder as Registry['settings.update_page_code']['types'],
  },
  'settings.integrations_api_tokens_page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/integrations/api-tokens',
    tokens: [{"old":"/admin/integrations/api-tokens","type":0,"val":"admin","end":""},{"old":"/admin/integrations/api-tokens","type":0,"val":"integrations","end":""},{"old":"/admin/integrations/api-tokens","type":0,"val":"api-tokens","end":""}],
    types: placeholder as Registry['settings.integrations_api_tokens_page']['types'],
  },
  'api_tokens.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/api-tokens',
    tokens: [{"old":"/api/admin/api-tokens","type":0,"val":"api","end":""},{"old":"/api/admin/api-tokens","type":0,"val":"admin","end":""},{"old":"/api/admin/api-tokens","type":0,"val":"api-tokens","end":""}],
    types: placeholder as Registry['api_tokens.index']['types'],
  },
  'api_tokens.store': {
    methods: ["POST"],
    pattern: '/api/admin/api-tokens',
    tokens: [{"old":"/api/admin/api-tokens","type":0,"val":"api","end":""},{"old":"/api/admin/api-tokens","type":0,"val":"admin","end":""},{"old":"/api/admin/api-tokens","type":0,"val":"api-tokens","end":""}],
    types: placeholder as Registry['api_tokens.store']['types'],
  },
  'api_tokens.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/api-tokens/:id',
    tokens: [{"old":"/api/admin/api-tokens/:id","type":0,"val":"api","end":""},{"old":"/api/admin/api-tokens/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/api-tokens/:id","type":0,"val":"api-tokens","end":""},{"old":"/api/admin/api-tokens/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api_tokens.destroy']['types'],
  },
  'plugins.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/plugins',
    tokens: [{"old":"/admin/plugins","type":0,"val":"admin","end":""},{"old":"/admin/plugins","type":0,"val":"plugins","end":""}],
    types: placeholder as Registry['plugins.page']['types'],
  },
  'plugins.menu': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/plugins/menu',
    tokens: [{"old":"/api/admin/plugins/menu","type":0,"val":"api","end":""},{"old":"/api/admin/plugins/menu","type":0,"val":"admin","end":""},{"old":"/api/admin/plugins/menu","type":0,"val":"plugins","end":""},{"old":"/api/admin/plugins/menu","type":0,"val":"menu","end":""}],
    types: placeholder as Registry['plugins.menu']['types'],
  },
  'plugins.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/plugins',
    tokens: [{"old":"/api/admin/plugins","type":0,"val":"api","end":""},{"old":"/api/admin/plugins","type":0,"val":"admin","end":""},{"old":"/api/admin/plugins","type":0,"val":"plugins","end":""}],
    types: placeholder as Registry['plugins.index']['types'],
  },
  'plugins.toggle': {
    methods: ["PUT"],
    pattern: '/api/admin/plugins/:name/toggle',
    tokens: [{"old":"/api/admin/plugins/:name/toggle","type":0,"val":"api","end":""},{"old":"/api/admin/plugins/:name/toggle","type":0,"val":"admin","end":""},{"old":"/api/admin/plugins/:name/toggle","type":0,"val":"plugins","end":""},{"old":"/api/admin/plugins/:name/toggle","type":1,"val":"name","end":""},{"old":"/api/admin/plugins/:name/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['plugins.toggle']['types'],
  },
  'modules.menu': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/modules/menu',
    tokens: [{"old":"/api/admin/modules/menu","type":0,"val":"api","end":""},{"old":"/api/admin/modules/menu","type":0,"val":"admin","end":""},{"old":"/api/admin/modules/menu","type":0,"val":"modules","end":""},{"old":"/api/admin/modules/menu","type":0,"val":"menu","end":""}],
    types: placeholder as Registry['modules.menu']['types'],
  },
  'settings.nav_config': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/nav-config',
    tokens: [{"old":"/api/admin/nav-config","type":0,"val":"api","end":""},{"old":"/api/admin/nav-config","type":0,"val":"admin","end":""},{"old":"/api/admin/nav-config","type":0,"val":"nav-config","end":""}],
    types: placeholder as Registry['settings.nav_config']['types'],
  },
  'modules.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/modules',
    tokens: [{"old":"/api/admin/modules","type":0,"val":"api","end":""},{"old":"/api/admin/modules","type":0,"val":"admin","end":""},{"old":"/api/admin/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['modules.index']['types'],
  },
  'modules.toggle': {
    methods: ["PUT"],
    pattern: '/api/admin/modules/:name/toggle',
    tokens: [{"old":"/api/admin/modules/:name/toggle","type":0,"val":"api","end":""},{"old":"/api/admin/modules/:name/toggle","type":0,"val":"admin","end":""},{"old":"/api/admin/modules/:name/toggle","type":0,"val":"modules","end":""},{"old":"/api/admin/modules/:name/toggle","type":1,"val":"name","end":""},{"old":"/api/admin/modules/:name/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['modules.toggle']['types'],
  },
  'v1.content.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/content',
    tokens: [{"old":"/api/v1/content","type":0,"val":"api","end":""},{"old":"/api/v1/content","type":0,"val":"v1","end":""},{"old":"/api/v1/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['v1.content.index']['types'],
  },
  'v1.content.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/content/:id',
    tokens: [{"old":"/api/v1/content/:id","type":0,"val":"api","end":""},{"old":"/api/v1/content/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/content/:id","type":0,"val":"content","end":""},{"old":"/api/v1/content/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['v1.content.show']['types'],
  },
  'v1.content.store': {
    methods: ["POST"],
    pattern: '/api/v1/content',
    tokens: [{"old":"/api/v1/content","type":0,"val":"api","end":""},{"old":"/api/v1/content","type":0,"val":"v1","end":""},{"old":"/api/v1/content","type":0,"val":"content","end":""}],
    types: placeholder as Registry['v1.content.store']['types'],
  },
  'v1.content.update': {
    methods: ["PUT"],
    pattern: '/api/v1/content/:id',
    tokens: [{"old":"/api/v1/content/:id","type":0,"val":"api","end":""},{"old":"/api/v1/content/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/content/:id","type":0,"val":"content","end":""},{"old":"/api/v1/content/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['v1.content.update']['types'],
  },
  'v1.content.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/content/:id',
    tokens: [{"old":"/api/v1/content/:id","type":0,"val":"api","end":""},{"old":"/api/v1/content/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/content/:id","type":0,"val":"content","end":""},{"old":"/api/v1/content/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['v1.content.destroy']['types'],
  },
  'v1.cms.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cms/:key/records',
    tokens: [{"old":"/api/v1/cms/:key/records","type":0,"val":"api","end":""},{"old":"/api/v1/cms/:key/records","type":0,"val":"v1","end":""},{"old":"/api/v1/cms/:key/records","type":0,"val":"cms","end":""},{"old":"/api/v1/cms/:key/records","type":1,"val":"key","end":""},{"old":"/api/v1/cms/:key/records","type":0,"val":"records","end":""}],
    types: placeholder as Registry['v1.cms.index']['types'],
  },
  'v1.cms.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cms/:key/records/:id',
    tokens: [{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/v1/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/v1/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['v1.cms.show']['types'],
  },
  'v1.cms.store': {
    methods: ["POST"],
    pattern: '/api/v1/cms/:key/records',
    tokens: [{"old":"/api/v1/cms/:key/records","type":0,"val":"api","end":""},{"old":"/api/v1/cms/:key/records","type":0,"val":"v1","end":""},{"old":"/api/v1/cms/:key/records","type":0,"val":"cms","end":""},{"old":"/api/v1/cms/:key/records","type":1,"val":"key","end":""},{"old":"/api/v1/cms/:key/records","type":0,"val":"records","end":""}],
    types: placeholder as Registry['v1.cms.store']['types'],
  },
  'v1.cms.update': {
    methods: ["PUT"],
    pattern: '/api/v1/cms/:key/records/:id',
    tokens: [{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/v1/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/v1/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['v1.cms.update']['types'],
  },
  'v1.cms.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/cms/:key/records/:id',
    tokens: [{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"cms","end":""},{"old":"/api/v1/cms/:key/records/:id","type":1,"val":"key","end":""},{"old":"/api/v1/cms/:key/records/:id","type":0,"val":"records","end":""},{"old":"/api/v1/cms/:key/records/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['v1.cms.destroy']['types'],
  },
  'admin.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/announcements',
    tokens: [{"old":"/admin/announcements","type":0,"val":"admin","end":""},{"old":"/admin/announcements","type":0,"val":"announcements","end":""}],
    types: placeholder as Registry['admin.page']['types'],
  },
  'admin.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/announcements',
    tokens: [{"old":"/api/admin/announcements","type":0,"val":"api","end":""},{"old":"/api/admin/announcements","type":0,"val":"admin","end":""},{"old":"/api/admin/announcements","type":0,"val":"announcements","end":""}],
    types: placeholder as Registry['admin.index']['types'],
  },
  'admin.store': {
    methods: ["POST"],
    pattern: '/api/admin/announcements',
    tokens: [{"old":"/api/admin/announcements","type":0,"val":"api","end":""},{"old":"/api/admin/announcements","type":0,"val":"admin","end":""},{"old":"/api/admin/announcements","type":0,"val":"announcements","end":""}],
    types: placeholder as Registry['admin.store']['types'],
  },
  'admin.update': {
    methods: ["PUT"],
    pattern: '/api/admin/announcements/:id',
    tokens: [{"old":"/api/admin/announcements/:id","type":0,"val":"api","end":""},{"old":"/api/admin/announcements/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/announcements/:id","type":0,"val":"announcements","end":""},{"old":"/api/admin/announcements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.update']['types'],
  },
  'admin.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/announcements/:id',
    tokens: [{"old":"/api/admin/announcements/:id","type":0,"val":"api","end":""},{"old":"/api/admin/announcements/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/announcements/:id","type":0,"val":"announcements","end":""},{"old":"/api/admin/announcements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.destroy']['types'],
  },
  'public.page': {
    methods: ["GET","HEAD"],
    pattern: '/announcements',
    tokens: [{"old":"/announcements","type":0,"val":"announcements","end":""}],
    types: placeholder as Registry['public.page']['types'],
  },
  'ctrl.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/tasks',
    tokens: [{"old":"/admin/tasks","type":0,"val":"admin","end":""},{"old":"/admin/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['ctrl.page']['types'],
  },
  'ctrl.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/tasks',
    tokens: [{"old":"/api/admin/tasks","type":0,"val":"api","end":""},{"old":"/api/admin/tasks","type":0,"val":"admin","end":""},{"old":"/api/admin/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['ctrl.index']['types'],
  },
  'ctrl.assignees': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/tasks/assignees',
    tokens: [{"old":"/api/admin/tasks/assignees","type":0,"val":"api","end":""},{"old":"/api/admin/tasks/assignees","type":0,"val":"admin","end":""},{"old":"/api/admin/tasks/assignees","type":0,"val":"tasks","end":""},{"old":"/api/admin/tasks/assignees","type":0,"val":"assignees","end":""}],
    types: placeholder as Registry['ctrl.assignees']['types'],
  },
  'ctrl.store': {
    methods: ["POST"],
    pattern: '/api/admin/tasks',
    tokens: [{"old":"/api/admin/tasks","type":0,"val":"api","end":""},{"old":"/api/admin/tasks","type":0,"val":"admin","end":""},{"old":"/api/admin/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['ctrl.store']['types'],
  },
  'ctrl.move': {
    methods: ["PATCH"],
    pattern: '/api/admin/tasks/:id/move',
    tokens: [{"old":"/api/admin/tasks/:id/move","type":0,"val":"api","end":""},{"old":"/api/admin/tasks/:id/move","type":0,"val":"admin","end":""},{"old":"/api/admin/tasks/:id/move","type":0,"val":"tasks","end":""},{"old":"/api/admin/tasks/:id/move","type":1,"val":"id","end":""},{"old":"/api/admin/tasks/:id/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['ctrl.move']['types'],
  },
  'ctrl.update': {
    methods: ["PUT"],
    pattern: '/api/admin/tasks/:id',
    tokens: [{"old":"/api/admin/tasks/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tasks/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tasks/:id","type":0,"val":"tasks","end":""},{"old":"/api/admin/tasks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['ctrl.update']['types'],
  },
  'ctrl.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/tasks/:id',
    tokens: [{"old":"/api/admin/tasks/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tasks/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tasks/:id","type":0,"val":"tasks","end":""},{"old":"/api/admin/tasks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['ctrl.destroy']['types'],
  },
  'pages_public.show': {
    methods: ["GET","HEAD"],
    pattern: '/*',
    tokens: [{"old":"/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['pages_public.show']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
